name: Test
permissions:
    contents: read

on:
    pull_request:
    workflow_dispatch:

# Cancel any currently running builds to save GitHub Actions hours.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-suite:
        name: Test suite
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Read .bun-version
              run: echo "GITHUB_BUN_VERSION=$(cat .bun-version)" >> $GITHUB_ENV

            - name: Set up Bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
              with:
                  bun-version: ${{ env.GITHUB_BUN_VERSION }}

            - name: Install dependencies
              run: bun install

            # Errors in Svelte check script cause this job to fail
            # See: https://svelte.dev/docs/cli/sv-check
            - name: Svelte check
              run: bun run check

            # Errors in Prettier check script cause this job to fail
            # See: https://prettier.io/docs/cli#--check
            - name: Prettier format check
              run: bun run format:check

            - name: Run test suite
              run: bun run test

            # Treat failures in the Vite build as test failures.
            # We don't need to keep the artifact of this build,
            # we just care that it completes successfully.
            - name: Run Vite build
              run: bun run build
